version: '3.4'

services:
  app:
    container_name: twittertracker
    image: ${DOCKER_REGISTRY}twittertracker
    build:
      context: .
      dockerfile: ./Dockerfile 
    ports:
      - "80:8080"
    volumes:
      - sharedfiles:/app/sharedfiles/
 